--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/Kieran/wallpaper/apple-light.jpg"

-- Special
background="#0B1118"
foreground="#e1cec2"
cursor="#e1cec2"

-- Colors
color0="#0B1118"
color1="#5E535B"
color2="#A56046"
color3="#9A6C60"
color4="#B7866C"
color5="#D29674"
color6="#777285"
color7="#e1cec2"
color8="#9d9087"
color9="#5E535B"
color10="#A56046"
color11="#9A6C60"
color12="#B7866C"
color13="#D29674"
color14="#777285"
color15="#e1cec2"
