# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

# App-specific floating rules
windowrule = match:title ^(pavucontrol)$, float 1
windowrule = match:title ^(blueman-manager)$, float 1
windowrule = match:title ^(nm-connection-editor)$, float 1
windowrule = match:title ^(qalculate-gtk)$, float 1

# Kitty terminal sizing
windowrule = match:class ^(kitty)$, float 1
windowrule = match:class ^(kitty)$, size 50% 60%

# Picture-in-Picture rules
windowrule = match:title ^(Picture-in-Picture)$, float 1
windowrule = match:title ^(Picture-in-Picture)$, pin 1
windowrule = match:title ^(Picture-in-Picture)$, size 34% 30%
windowrule = match:title ^(Picture-in-Picture)$, opacity 1.0 override 1.0 override
# windowrule = float,title:^(pavucontrol)$
# windowrule = float,title:^(blueman-manager)$
# windowrule = float,title:^(nm-connection-editor)$
# windowrule = float,title:^(qalculate-gtk)$
#
# windowrule = float,title:^(kitty)$
# windowrule = size 50% 60%,title: (^kitty)$
#
# windowrule = float,title:^(Picture-in-Picture)$
# windowrule = pin,title:^(Picture-in-Picture)$
# windowrule = size 34% 30%, title:^(Picture-in-Picture)$
# windowrule = opacity 1.0 override 1.0 override, title:^(Picture-in-Picture)$


# windowrule = float,class:^(uk.ac.nott.cs.comp2013.frogger.Main)$


#windowrule = opacity 1.0 override 0.9 override, ^(firefox)$
# windowrule = opacity 1.0 override 0.7 override, ^(firefox)$
